# Generated by Django 5.2.17 on 2026-09-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_professional_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_kind', models.CharField(choices=[('avatar', 'Avatar'), ('logo', 'Logo')], max_length=10)),
                ('name', models.CharField(max_length=512)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
