# Generated by Django 5.2.16 on 2026-08-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILURE', 'Fallido'), ('DENIED', 'Denegado'), ('BLOCKED', 'Bloqueado')], max_length=10)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('patient_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['action', 'occurred_at'], name='audit_action_date_idx'), models.Index(fields=['actor_id', 'occurred_at'], name='audit_actor_date_idx'), models.Index(fields=['patient_id', 'occurred_at'], name='audit_patient_date_idx'), models.Index(fields=['resource_type', 'resource_id', 'occurred_at'], name='audit_resource_date_idx')],
            },
        ),
    ]
