# Generated by Django 5.2.16 on 2026-08-08 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='education',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='information_reliability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='information_source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='origin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_name', models.CharField(blank=True, max_length=200)),
                ('examiner_national_id', models.CharField(blank=True, max_length=32)),
                ('inss_number', models.CharField(blank=True, max_length=40)),
                ('cema_number', models.CharField(blank=True, max_length=40)),
                ('consultation_date', models.DateField(blank=True, null=True)),
                ('consultation_time', models.TimeField(blank=True, null=True)),
                ('dental_service', models.CharField(blank=True, max_length=200)),
                ('chief_complaint', models.TextField(blank=True)),
                ('present_illness_history', models.TextField(blank=True)),
                ('respiratory', models.TextField(blank=True)),
                ('cardiovascular', models.TextField(blank=True)),
                ('hepatic_renal', models.TextField(blank=True)),
                ('gastrointestinal', models.TextField(blank=True)),
                ('neurological', models.TextField(blank=True)),
                ('blood_system', models.TextField(blank=True)),
                ('reproductive_organs', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('infectious_diseases', models.JSONField(blank=True, default=dict)),
                ('hereditary_diseases', models.JSONField(blank=True, default=dict)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_surface_area', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('general_appearance', models.TextField(blank=True)),
                ('skin_and_mucosa', models.TextField(blank=True)),
                ('thorax', models.TextField(blank=True)),
                ('rib_cage', models.TextField(blank=True)),
                ('breasts', models.TextField(blank=True)),
                ('lung_fields', models.TextField(blank=True)),
                ('cardiac', models.TextField(blank=True)),
                ('abdomen_pelvis', models.TextField(blank=True)),
                ('rectal_exam', models.TextField(blank=True)),
                ('musculoskeletal', models.TextField(blank=True)),
                ('upper_extremities', models.TextField(blank=True)),
                ('lower_extremities', models.TextField(blank=True)),
                ('genitourinary', models.TextField(blank=True)),
                ('gynecological_exam', models.TextField(blank=True)),
                ('neurological_exam', models.TextField(blank=True)),
                ('observations_analysis', models.TextField(blank=True)),
                ('dental_diagnoses', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('budget', models.TextField(blank=True)),
                ('treatment_performed', models.TextField(blank=True)),
                ('radiographic_exams', models.JSONField(blank=True, default=list)),
                ('clinical_photographs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='patients.patient')),
            ],
        ),
    ]
