# Generated by Django 5.2.16 on 2026-08-08 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_education_patient_father_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consultation_type', models.CharField(choices=[('VALORACION_INICIAL', 'Valoración inicial'), ('GENERAL', 'Consulta general'), ('SEGUIMIENTO', 'Seguimiento'), ('URGENCIA', 'Urgencia')], max_length=24)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('COMPLETADA', 'Completada'), ('EN_PROGRESO', 'En progreso'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['patient', '-date'], name='patients_co_patient_1102b7_idx')],
            },
        ),
    ]
