# Generated by Django 5.2.16 on 2026-08-08 22:46

from django.db import migrations, models


def populate_professional_name_snapshots(apps, schema_editor):
    consultation_model = apps.get_model('patients', 'Consultation')
    for consultation in consultation_model.objects.select_related('professional'):
        professional = consultation.professional
        full_name = f"{professional.first_name} {professional.last_name}".strip()
        consultation.professional_name_snapshot = full_name or professional.email
        consultation.save(update_fields=['professional_name_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='abdomen_pelvis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='blood_system',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='body_surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='breasts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='budget',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='cardiac',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='cardiovascular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='cema_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dental_diagnoses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dental_service',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultation',
            name='examiner_national_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='consultation',
            name='gastrointestinal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='general_appearance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='genitourinary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='gynecological_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hepatic_renal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='inss_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lower_extremities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='lung_fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='musculoskeletal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='neurological',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='neurological_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='observations_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='present_illness_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='professional_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rectal_exam',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reproductive_organs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='respiratory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rib_cage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='skin_and_mucosa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='thorax',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_performed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='upper_extremities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RunPython(populate_professional_name_snapshots, migrations.RunPython.noop),
    ]
