# Generated by Django 5.2.17 on 2026-08-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0010_consultation_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('diagnosis_text', models.TextField(blank=True)),
                ('tooth_code', models.CharField(blank=True, max_length=2, null=True)),
                ('surfaces', models.JSONField(blank=True, default=list)),
                ('planned_finding', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('ACEPTADO', 'Aceptado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PROPUESTO', max_length=16)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_items', to='patients.consultation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_items', to='clinics.clinicservice')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
