# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_treatmentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentitem",
            name="performed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentitem",
            name="performed_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_treatment_items",
                to="patients.consultation",
            ),
        ),
        migrations.AddField(
            model_name="treatmentitem",
            name="status_reason",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
