# Generated by Django 5.2.17 on 2026-09-02 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_contract_legacy_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='patients.consultation'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='tooth_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='patientdocument',
            index=models.Index(fields=['patient', 'consultation'], name='patient_doc_consult_idx'),
        ),
    ]
