# Generated by Django 5.2.17 on 2026-09-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patientdocument_consultation_and_tooth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='treatmentitem',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
