# Generated by Django 5.2.17 on 2026-09-06 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_clinical_edit_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_patient_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='deletion_reason',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
    ]
