# Generated by Django 5.2.16 on 2026-08-09 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_odontogramversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos'), (90, '90 minutos')])),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=16)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dental_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ('date', 'start_time', 'dentist__first_name', 'dentist__last_name'),
                'indexes': [models.Index(fields=['date', 'start_time'], name='appointment_date_85ff09_idx'), models.Index(fields=['dentist', 'date'], name='appointment_dentist_05d199_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_83aa7a_idx')],
            },
        ),
    ]
