# Generated by Django 5.2.17 on 2026-09-01 20:54

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class RemovePostgresConstraint(migrations.RemoveConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class AddPostgresConstraint(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_validate_appointment_consultation'),
        ('clinics', '0001_initial'),
        ('patients', '0015_contract_legacy_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRescheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField()),
                ('previous_start_time', models.TimeField()),
                ('previous_duration_minutes', models.PositiveSmallIntegerField()),
                ('new_date', models.DateField()),
                ('new_start_time', models.TimeField()),
                ('new_duration_minutes', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        RemovePostgresConstraint(
            model_name='appointment',
            name='appointment_dentist_schedule_excl',
        ),
        RemovePostgresConstraint(
            model_name='appointment',
            name='appointment_patient_schedule_excl',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='appointment',
                    name='status',
                    field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('PRESENTE', 'Presente'), ('EN_ATENCION', 'En atención'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=16),
                ),
            ],
        ),
        AddPostgresConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('PROGRAMADA', 'CONFIRMADA', 'PRESENTE', 'EN_ATENCION', 'COMPLETADA', 'NO_ASISTIO'))), expressions=(('dentist', '='), ('scheduled_range', '&&')), name='appointment_dentist_schedule_excl'),
        ),
        AddPostgresConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('PROGRAMADA', 'CONFIRMADA', 'PRESENTE', 'EN_ATENCION', 'COMPLETADA', 'NO_ASISTIO'))), expressions=(('patient', '='), ('scheduled_range', '&&')), name='appointment_patient_schedule_excl'),
        ),
        migrations.AddField(
            model_name='appointmentrescheduleevent',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_events', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentrescheduleevent',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_reschedule_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appointmentrescheduleevent',
            index=models.Index(fields=['appointment', '-created_at'], name='appt_reschedule_history_idx'),
        ),
    ]
